### ISSUE TITLE
Files missing from gem

### ISSUE THREAD

**Issue by dark-panda** [evanphx/benchmark-ips#103] opened 2020-05-04 14:53 UTC
It appears a few files are missing from the gem file for the 2.8.0 release. A couple of files reference `StatsMetric`, which is defined in `lib/benchmark/ips/stats/stats_metric.rb`, but that file is not included in the released gem file.

**Comment by pedros007** [comment] 2020-05-04 14:55
Duplicate of #101

**Closed** 2020-05-04 21:22 UTC
